services:
  autorun-web:
    image: nginx:alpine
    container_name: autorun-web
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./og.png:/usr/share/nginx/html/og.png:ro
      - ./fonts:/usr/share/nginx/html/fonts:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
